### ISSUE TITLE
Deploy static React app on GCP

### ISSUE THREAD

**Issue by youjeongsue** [youjeongsue/Today-I-Learned#4]
1. React 앱 준비, build
```
npm run build
```
2. 버킷 만들기
3. build 폴더 버킷에 올리기
4. app.yaml 파일 만들기
```
//app.yaml

runtime: nodejs10
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /(.*)$
    static_files: build/\1
    upload: build/(.*)
```
5. shell에서 설정
```
mkdir hello-react
gsutil rsync -r gs://hello-react ./hello-react
cd hello-react
gcloud app deploy
```

참고: https://medium.com/wesionary-team/deploy-your-static-react-application-on-google-cloud-platform-bc8afb9b9b6
